# Fichier de configuration du module Base

# nom des feuilles de style CSS à utiliser
# doit être sous forme de tableau car on peut en avoir plusieurs
#CSS: [xxx.css]
CSS: [formulaire.css]

# fichiers javascript à inclure
# doit être sous forme de tableau car on peut en avoir plusieurs
#JS: [xxx.js]

#title: aaaaa

database: ascodocpsy

autoinclude: templates/autoincludes/row.html

# Url de base d'un article sous SPIP
urlarticle: 'http://www.ascodocpsy.org/article.php3?id_article='

filter:
    AdminBase:
    EditBase:
    cli:
    default: '(* sauf type=periodique) and Valide=vrai'

searchform:
    template: templates/search.html

search:
    template: templates/list.html
    errortemplate: templates/error/error_base.html
    noanswertemplate: templates/error/error_base_noanswer.html
    JS: [asco.js]
    callback: getField
    
replaceform:
    access: AdminBase
    template: templates/replaceform.html
    
replace:
    access: AdminBase
    template: templates/replaced.html

show:
    template: templates/show.html
    callback: getField

load:
    access: AdminBase,EditBase
    JS: [autosize.js, controls.js, load.js]
    template: templates/load/load.html
    callback: getDates

loadfull:
    action: load
    access: AdminBase
    JS: [autosize.js, controls.js, load.js]
    template: templates/load/load.html
    callback: getDates
    
new:
    access: AdminBase, EditBase
    template: templates/load/load.html
    callback: emptyString

save:
#    access: AdminBase,EditBase
    callback: validData
	
delete:
    access: AdminBase
    template: templates/deleted.html

locate:
    access: AdminBase,EditBase
    template: templates/show.html
    errortemplate: templates/error/error.html

inform:
    template: templates/show.html
    errortemplate: templates/error/error.html

import:
    access: AdminBase,EditBase

importfiles:
    access: cli

sort:
    access: cli, AdminBase
    sortkey: 'Date:DateText:CongrDat,8,KeyDate,+ ; Type,20,KeyTextIgnoreCase,+ ; Rev,50,KeyTextIgnoreCase,-'

validateall:
    access: AdminBase

# Panier de notices
addToCart:
  sessions:
    use: true
  errortemplate: templates/error/error.html

removeFromCart:
  errortemplate: templates/error/error.html

clearCart:
  sessions:
    use: true

exportCart:
  sessions:
    use: true
  errortemplate: templates/error/error.html

exportCartByType:
  sessions:
    use: true
  errortemplate: templates/error/error.html

showCart:
  access: AdminBase, EditBase
  sessions:
    use: true
