# nom des feuilles de style CSS à utiliser
# doit être sous forme de tableau car on peut en avoir plusieurs
#CSS: [xxx.css]

# fichiers javascript à inclure
# doit être sous forme de tableau car on peut en avoir plusieurs
#JS: [xxx.js]

#title: fdsfsdlkfjdskhl

database: ascodocpsy

filter:
    AdminBase:
    EditBase:
    default: '(* sauf type=periodique)'
# quand + de données : '(* sauf type=periodique) and Valide=vrai'

search:
    template:
        AdminBase: templates/member_search.yaml
        EditBase: templates/member_search.yaml
        default: templates/public_search.yaml
    list:
        AdminBase: templates/member_list.yaml
        EditBase: templates/member_list.yaml
        default: templates/public_list.yaml
    callback: none

show:
    template:
        AdminBase: templates/member_show.yaml
        EditBase: templates/member_show.yaml
        default: templates/public_show.yaml
    
load:
    access: AdminBase,EditBase
    JS: [autosize.js, controls.js, load.js]
    template: templates/load/load.yaml
    callback: none

save:
    access: AdminBase,EditBase

delete:
    access: AdminBase

sort:
  sortkey: 'Date:DateText:CongrDat,8,KeyDateBdsp ; Type,20,KeyTextIgnoreCase ; Rev,50,KeyTextIgnoreCase'

# Panier de notices
addToCart:
  sessions:
    use: true
clearCart:
  sessions:
    use: true
exportCart:
  sessions:
    use: true
showCart:
  sessions:
    use: true
