# thème général du site (deux options possibles pour le moment: asco, poivron)
theme: ascodocpsy

# structure générale des pages par défaut
layout: asco.html

# nom des feuilles de style CSS à utiliser
# doit être sous forme de tableau car on peut en avoir plusieurs
CSS: [asco.css]

# fichiers javascript à inclure
# doit être sous forme de tableau car on peut en avoir plusieurs
JS: 
  - /fabweb/js/lib/jquery/1.1.2/jquery-latest.pack.js
  - /fabweb/js/lib/interface/1.2/interface.js
  - /fabweb/js/lib/jquery.form/jquery.form.js
