# Fichier de configuration du module AscoCart

# AscoCart est un pseudo module qui hérite de CartModule
module: CartModule

CSS: [formulaire.css]

JS:
  - /fabweb/js/lib/jquery/jquery-1.2.1.min.js

#add:
#  template: 

remove:
  template: removed.html

clear:
  template: cleared.html

show:
  template: show.html
