# Fichier de configuration du module AscoCart

# AscoCart est un pseudo module qui hérite de CartModule
module: CartModule

# Nom du panier -> Intérêt ?
#name: panier

add:
  template: added.html

#remove:

#clear:

show:
  template: show.html
